# Generated by Django 5.1.4 on 2025-02-11 09:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="I am a vendor", null=True
            ),
        ),
    ]
